package vn.iotstar.Entity;

import javax.persistence.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;


@AllArgsConstructor
@NoArgsConstructor
@Builder // Viết method nối chuỗi
@Data
@Entity// tạo ra get set
@DynamoDBTable(tableName = "grade") 
public class Grade {
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
    private int id;
	
	@DynamoDBAttribute
    private int mssv;
	
	@DynamoDBAttribute
    private float grade;
	
	@DynamoDBAttribute
	private String subjectGroupId;
	
	@DynamoDBAttribute
	private int deleted ;

	
}
