package vn.iotstar.Entity;

import javax.persistence.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;


@AllArgsConstructor
@NoArgsConstructor
@Builder // Viết method nối chuỗi
@Data
@Entity// tạo ra get set
@DynamoDBTable(tableName = "grade") 
public class Grade {
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
    private String id;
	
	@DynamoDBAttribute
    private int mssv;
	
	@DynamoDBAttribute
    private float grade;
	
	@DynamoDBAttribute
	private String subjectId;
	
	@DynamoDBAttribute
	private int deleted ;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public int getMssv() {
		return mssv;
	}

	public void setMssv(int mssv) {
		this.mssv = mssv;
	}

	public float getGrade() {
		return grade;
	}

	public void setGrade(float grade) {
		this.grade = grade;
	}

	public String getSubjectId() {
		return subjectId;
	}

	public void setSubjectId(String subjectId) {
		this.subjectId = subjectId;
	}

	public int getDeleted() {
		return deleted;
	}

	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}	
}
