package vn.iotstar.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;


@AllArgsConstructor
@NoArgsConstructor
@Builder // Viết method nối chuỗi
@Data // tạo ra get set
@DynamoDBTable(tableName = "grade") 
public class Grade {
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
    private String studentId;
	
	@DynamoDBAttribute
    private String subjectId;
	
	@DynamoDBAttribute
    private double grade;

	/**
	 * @return the studentId
	 */
	public String getStudentId() {
		return studentId;
	}

	/**
	 * @param studentId the studentId to set
	 */
	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	/**
	 * @return the subjectId
	 */
	public String getSubjectId() {
		return subjectId;
	}

	/**
	 * @param subjectId the subjectId to set
	 */
	public void setSubjectId(String subjectId) {
		this.subjectId = subjectId;
	}

	/**
	 * @return the grade
	 */
	public double getGrade() {
		return grade;
	}

	/**
	 * @param grade the grade to set
	 */
	public void setGrade(double grade) {
		this.grade = grade;
	}

	public Grade(String subjectId, double grade) {
		super();
		this.subjectId = subjectId;
		this.grade = grade;
	}

	public Grade() {
		// TODO Auto-generated constructor stub
	}
}
