package vn.iotstar.Entity;

import java.io.Serializable;

import javax.persistence.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@SuppressWarnings("serial")
@Builder // Viết method nối chuỗi
@Data
@Entity // tạo ra get set
@DynamoDBTable(tableName = "studentclass")
public class StudentClass implements Serializable{
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
    private String id;
	@DynamoDBAttribute
    private String name;
	@DynamoDBAttribute
    private String facultyId;
    
    @DynamoDBAttribute
    private int deleted;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFacultyId() {
		return facultyId;
	}

	public void setFacultyId(String facultyId) {
		this.facultyId = facultyId;
	}

	public int getDeleted() {
		return deleted;
	}

	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}

	public StudentClass(String id, String name, String facultyId, int deleted) {
		super();
		this.id = id;
		this.name = name;
		this.facultyId = facultyId;
		this.deleted = deleted;
	}

	public StudentClass() {
		super();
	}
    
    
}
