package vn.iotstar.Entity;

import java.io.Serializable;

import javax.persistence.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@SuppressWarnings("serial")
@AllArgsConstructor
@NoArgsConstructor
@Builder // Viết method nối chuỗi
@Data
@Entity // tạo ra get set
@DynamoDBTable(tableName = "student")
public class Student implements Serializable {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private int mssv;

	@DynamoDBAttribute
	private String studentClassId;
	@DynamoDBAttribute
	private String name;
	@DynamoDBAttribute
	private String birthday;
	@DynamoDBAttribute
	private String image;
	@DynamoDBAttribute
	private String address;
	@DynamoDBAttribute
	private String gender;
	@DynamoDBAttribute
	private String phone;
	@DynamoDBAttribute
	private int deleted;

}
