use  QLSV
go
insert into Faculty values('Công nghệ thông tin')
insert into Faculty values('Đào tạo chất lượng cao')
insert into Faculty values('Điện điện tử')

insert into Class values('Toán học','2020',1)
insert into Class values('Lý học','2020',1)
insert into Class values('Hóa học','2020',2)
insert into Class values('Sinh học','2020',2)
insert into Class values('Sử học','2020',2)


insert into Student values( 'Nguyễn Thiên Khang','03-12-2002', 'https://img.freepik.com/free-photo/happy-young-female-student-holding-notebooks-from-courses-smiling-camera-standing-spring-clothes-against-blue-background_1258-70161.jpg','Đồng Tháp','Male',1)
insert into Student values( 'Bùi Đặng Quốc Chí','03-12-2002', '','Quảng Ngãi','Male',2)
insert into Student values( 'Ngô Diệp Quang Huy','03-12-2002', '','Gia Lai','Male',3)
insert into Student values( 'Nguyễn Hoàng Toàn','07-02-2002', 'https://img.freepik.com/free-photo/happy-young-female-student-holding-notebooks-from-courses-smiling-camera-standing-spring-clothes-against-blue-background_1258-70161.jpg','Tây Ninh','Male',1)
insert into Student values( 'Võ Hồng Khang','22-07-2002', 'https://img.freepik.com/free-photo/happy-young-female-student-holding-notebooks-from-courses-smiling-camera-standing-spring-clothes-against-blue-background_1258-70161.jpg','An Giang','Male',2)
insert into Student values( 'Nguyễn Công Thành','13-8-2002', 'https://img.freepik.com/free-photo/front-view-male-student-dark-t-shirt-yellow-backpack-holding-files-books-smiling-light-blue-wall_140725-46715.jpg','Tiền Giang','Male',3)
insert into Student values( 'Phan Văn Đức Anh','02-11-2002', '','Bình Định','Male',2)
insert into Student values( 'Nguyễn Đình Thiện','28-3-2002', 'https://img.freepik.com/free-photo/front-view-male-student-dark-t-shirt-yellow-backpack-holding-files-books-smiling-light-blue-wall_140725-46715.jpg','Khánh Hòa','Male',1)
insert into Student values( 'Trần Văn Kiệt','15-6-2002','','Huế','Male',2)


insert into Subjects values('1', 'Haa dai cuong',3)
insert into Subjects values('2', 'Cong nghe phan mem',3 )
insert into Subjects values('3', 'Lap trinh web',3 )
insert into Subjects values('4', 'Thuong mai dien tu',3 )
insert into Subjects values('5', 'Dien toan dam may',3 )
insert into Subjects values('6', 'An toan thong tin',3 )
insert into Subjects values('7', 'Co so du lieu',3)
insert into Subjects values('8', 'Hoc may',3 )



insert into Points values('1', '1','6')
insert into Points values('1', '2','1')
insert into Points values('1', '3','4')
insert into Points values('1', '4','2')
insert into Points values('1', '5','6')
insert into Points values('1', '6','1')
insert into Points values('1', '7','8')
insert into Points values('1', '8','2')
insert into Points values('1', '9','2')
insert into Points values('2', '1','8')
insert into Points values('2', '2','6')
insert into Points values('2', '3','5')
insert into Points values('3', '8','7')
insert into Points values('3', '9','7')
insert into Points values('4', '1','1')
insert into Points values('4', '2','4')
insert into Points values('4', '3','3')
insert into Points values('4', '4','5')
insert into Points values('4', '5','2')
insert into Points values('4', '6','1')
insert into Points values('4', '7','8')
insert into Points values('4', '8','2')
insert into Points values('4', '9','6')
insert into Points values('5', '1','4')
insert into Points values('5', '2','5')
insert into Points values('5', '3','8')
insert into Points values('5', '4','8')
insert into Points values('5', '5','7')
insert into Points values('5', '6','6')
insert into Points values('5', '7','1')
insert into Points values('5', '8','1')
insert into Points values('5', '9','7')
insert into Points values('6', '1','6')
insert into Points values('6', '2','2')
insert into Points values('6', '3','8')
insert into Points values('6', '4','7')
insert into Points values('6', '5','7')
insert into Points values('6', '6','8')
insert into Points values('6', '7','4')
insert into Points values('6', '8','1')
insert into Points values('6', '9','2')
insert into Points values('7', '1','8')
insert into Points values('7', '2','4')
insert into Points values('7', '3','7')
insert into Points values('7', '4','4')



insert into Teacher values(1,'Phạm Tuấn Trường',1,1,'HCM',0342423)
insert into Teacher values(2,'Nguyễn Văn Ninh',2,1,'HCM',0342423423)
insert into Teacher values(3,'Phạm Tuấn Trường',1,1,'HCM',0342423)
insert into Teacher values(4,'Phạm Tuấn Trường',1,1,'HCM',0342423)
insert into Teacher values(5,'Phạm Tuấn Trường',1,1,'HCM',0342423)

