package vn.iotstar.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;


@AllArgsConstructor
@NoArgsConstructor
@Builder // Viết method nối chuỗi
@Data // tạo ra get set
@DynamoDBTable(tableName = "Grade") 
public class Grade {
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
    private String studentId;
	
	@DynamoDBAttribute
    private String subjectId;
	
	@DynamoDBAttribute
    private double middleGrade;
	
	@DynamoDBAttribute
    private double finalGrade;
	
	@DynamoDBAttribute
    private int deleted;
	
	@DynamoDBAttribute
    private double totalGrade;


}
